"""Python port of the Flutter ReportService."""

from datetime import datetime

from ..models.ecg_record import ECGRecord
from ..models.user_profile import UserProfile


def generate_text_report(record: ECGRecord, profile: UserProfile | None) -> str:
    date_str = record.recorded_at.strftime("%B %d, %Y \u2013 %I:%M %p")
    now_str = datetime.now().strftime("%B %d, %Y")

    lines = [
        "CARDIOSCAN ECG REPORT",
        "=" * 30,
        "",
    ]

    name = profile.name if profile else record.patient_name
    age = _compute_age(profile.date_of_birth) if profile else record.patient_age
    gender = profile.gender if profile else record.patient_gender

    lines.append(f"Patient: {name}")
    lines.append(f"Age: {age} | Gender: {gender}")

    if profile and profile.medical_conditions:
        conditions = ", ".join(profile.medical_conditions)
        lines.append(f"Medical Conditions: {conditions}")
    if profile and profile.medications:
        lines.append(f"Medications: {profile.medications}")

    lines.append("")
    lines.append(f"Recording Date: {date_str}")
    lines.append(f"Heart Rate: {record.heart_rate} BPM")
    lines.append(f"Severity: {record.severity.upper()}")
    lines.append("")
    lines.append(f"Interpretation: {record.interpretation}")
    lines.append("")

    lines.append("Findings:")
    for f in record.findings:
        lines.append(f"  - {f}")
    lines.append("")

    if record.symptoms:
        lines.append("Symptoms at Time of Recording:")
        for s in record.symptoms:
            lines.append(f"  - {s}")
        if record.symptom_note:
            lines.append(f"Patient Note: {record.symptom_note}")
        lines.append("")

    if record.doctor_notes:
        lines.append(f"Doctor's Notes: {record.doctor_notes}")
        lines.append("")

    lines.append("=" * 30)
    lines.append(f"Generated by CardioScan on {now_str}")

    return "\n".join(lines)


def _compute_age(dob) -> int:
    today = datetime.now().date()
    age = today.year - dob.year
    if (today.month, today.day) < (dob.month, dob.day):
        age -= 1
    return age
