import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';
import '../models/ecg_record.dart';
import '../models/user_profile.dart';

class ReportService {
  static String generateTextReport(ECGRecord record, UserProfile? profile) {
    final dateStr = DateFormat('MMMM d, yyyy \u2013 h:mm a').format(record.timestamp);
    final now = DateFormat('MMMM d, yyyy').format(DateTime.now());

    final buf = StringBuffer();
    buf.writeln('CARDIOSCAN ECG REPORT');
    buf.writeln('=' * 30);
    buf.writeln();

    // Patient info
    buf.writeln('Patient: ${profile?.name ?? record.patientName}');
    buf.writeln('Age: ${profile?.age ?? record.patientAge} | Gender: ${profile?.gender ?? record.patientGender}');
    if (profile != null && profile.medicalConditions.isNotEmpty) {
      buf.writeln('Medical Conditions: ${profile.medicalConditions.join(', ')}');
    }
    if (profile?.medications != null && profile!.medications!.isNotEmpty) {
      buf.writeln('Medications: ${profile.medications}');
    }
    buf.writeln();

    // Recording info
    buf.writeln('Recording Date: $dateStr');
    buf.writeln('Heart Rate: ${record.heartRate} BPM');
    buf.writeln('Severity: ${record.severity.name.toUpperCase()}');
    buf.writeln();

    // Interpretation
    buf.writeln('Interpretation: ${record.interpretation}');
    buf.writeln();

    // Findings
    buf.writeln('Findings:');
    for (final f in record.findings) {
      buf.writeln('  - $f');
    }
    buf.writeln();

    // Symptoms
    if (record.symptoms.isNotEmpty) {
      buf.writeln('Symptoms at Time of Recording:');
      for (final s in record.symptoms) {
        buf.writeln('  - $s');
      }
      if (record.symptomNote != null && record.symptomNote!.isNotEmpty) {
        buf.writeln('Patient Note: ${record.symptomNote}');
      }
      buf.writeln();
    }

    // Doctor notes
    if (record.doctorNotes != null && record.doctorNotes!.isNotEmpty) {
      buf.writeln("Doctor's Notes: ${record.doctorNotes}");
      buf.writeln();
    }

    buf.writeln('=' * 30);
    buf.writeln('Generated by CardioScan on $now');

    return buf.toString();
  }

  static Future<void> shareReport(String reportText) async {
    await Share.share(reportText);
  }
}
